# Generated by Django 4.0.6 on 2022-08-18 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('project_start_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publication_date')),
                ('project_completion_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Completion date')),
                ('project_description', models.CharField(max_length=1000, verbose_name='Project Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-project_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, unique=True, verbose_name='Project Name')),
            ],
        ),
    ]
