# Generated by Django 4.0.6 on 2022-07-21 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('project_type', models.CharField(max_length=250, unique=True, verbose_name='Project Name')),
                ('project_start_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publication_date')),
                ('project_completion_date', models.DateTimeField(db_index=True, verbose_name='Completion date')),
                ('project_description', models.CharField(max_length=1000, verbose_name='Project Description')),
                ('project_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Project Author')),
                ('project_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executors', to=settings.AUTH_USER_MODEL, verbose_name='Project Executor')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-project_start_date'],
            },
        ),
    ]
