# Generated by Django 4.0.6 on 2022-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_completion_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Completion date'),
        ),
    ]
