# Generated by Django 4.0.6 on 2022-08-12 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executors_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Executor'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='projects.projecttype', verbose_name='Project Type'),
        ),
    ]
